/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckableTag: typeof import('ant-design-vue/es')['CheckableTag']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Button: typeof import('./src/_components/Button.vue')['default']
    IconLink: typeof import('./src/_components/icons/IconLink.vue')['default']
    IHugeiconsImage01: typeof import('~icons/hugeicons/image01')['default']
    ITablerLocationShare: typeof import('~icons/tabler/location-share')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
